Fixed BUILD_ARTIFACTS_DIR value to generic
kumahq/kuma pull request #1027
Opened 2020-09-17 13:22 UTC by nikita15p

Removed GOOS and GOARCH from BUILD_ARTIFACTS_DIR value. 

### Summary

In [developer doc](https://github.com/kumahq/kuma/blob/master/DEVELOPER.md),   step `export PATH=`pwd`/build/artifacts/kumactl:$PATH` does not match with the current value generated in make file for eg artifacts-linux-amd64 is generated instead of artifacts

### Full changelog
Present: BUILD_ARTIFACTS_DIR ?= $(BUILD_DIR)/artifacts-${GOOS}-${GOARCH} 
This PR: BUILD_ARTIFACTS_DIR ?= $(BUILD_DIR)/artifacts

### Issues resolved
Documentation https://github.com/kumahq/kuma/blob/master/DEVELOPER.md

### Documentation
https://github.com/kumahq/kuma/blob/master/DEVELOPER.md

2020-09-17 13:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kumahq/kuma?pullRequest=1027) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kumahq/kuma?pullRequest=1027) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kumahq/kuma?pullRequest=1027) it.</sub>

2020-09-17 13:27 UTC, nickolaev requested changes
This will break the workflow when compiling on OSX, where I do have:
```
artifacts-darwin-amd64/
artifacts-linux-amd64/
```

I suggest fixing the DEVELOPER.md instead.

2020-09-17 18:40 UTC, nikita15p commented
@nickolaev please review.

2020-09-18 07:31 UTC, nickolaev approved these changes
Thanks! That is a cool one-liner, although I'd probably go for `export GOOS=go env GOOS` and then use $GOOS in the PATH.

In any case - thanks for your contribution!

2020-09-18 07:32 UTC, merged