fix: fix miss makezero bug
kumahq/kuma pull request #10317
Opened 2024-05-26 16:21 UTC by alingse

### Checklist prior to review

I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.

see issues https://github.com/alingse/go-linter-runner/issues/1

and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9242968813/job/25426482280 

```
====================================================================================================
append to slice `orderedTags` with non-zero initialized length at https://github.com/kumahq/kuma/blob/master/api/common/v1alpha1/ref.go#L104:17
append to slice `combinedResources` with non-zero initialized length at https://github.com/kumahq/kuma/blob/master/app/kumactl/cmd/install/install_observability.go#L43:24
append to slice `combinedResources` with non-zero initialized length at https://github.com/kumahq/kuma/blob/master/app/kumactl/cmd/install/install_observability.go#L44:24
append to slice `combinedResources` with non-zero initialized length at https://github.com/kumahq/kuma/blob/master/app/kumactl/cmd/install/install_observability.go#L45:24
====================================================================================================
```

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2024-05-27 06:28 UTC, slonka commented
Hi! Thanks for your contribution, please add this linter to `.golangci.yml` - https://github.com/kumahq/kuma/blob/master/.golangci.yml#L2

2024-05-27 06:29 UTC, slonka requested changes
Hi! Thanks for your contribution, please add this linter to `.golangci.yml` - https://github.com/kumahq/kuma/blob/master/.golangci.yml#L2 - I would've done it myself but you did not allow maintainers to modify this PR.

2024-05-27 14:15 UTC, alingse commented
@slonka I have add `makezero` to `.golangci.yaml` ( but it may report some bad case in future)

2024-06-03 10:08 UTC, slonka approved these changes

2024-06-03 10:13 UTC, merged