fix(kds): fix the case when webhook/db reject resource
kumahq/kuma pull request #10315
Opened 2024-05-24 22:43 UTC by lukidzi

### Checklist prior to review

### Context

Lately we can observe that one specific [e2e test](https://github.com/kumahq/kuma/actions/runs/9212633408/job/25344974553) fails quite often. 
```
  [FAIL] Test upgrading Multizone with Helm chart [It] should sync policies from Global to Zone [job-2]
  github.com/kumahq/kuma/test/e2e/helm/kuma_helm_upgrade_multizone.go:135
```

It fails with specific errors which leads to situation where KDS resources were not synced correctly:

This case checks if we have 3 MeshTimeout policies (2 defaults and 1 created)
```
  Expected
      <int>: 1
  to equal
      <int>: 3
```

### Root cause

After debugging, I've noticed that we can reproduce this situation on K8s or manually (code/db change). It happens because mesh policies have an owner reference on the Mesh object. Once the Mesh object is not available on the cluster, default policies are rejected. Then, the [resource_retry_forcer](https://github.com/kumahq/kuma/blob/master/pkg/kds/v2/server/resource_retry_forcer.go#L101) sleeps for 5 seconds before forcing the snapshot to recalculate the state for the specific resource and send the changes again. Unfortunately, when more than one resource type fails, it recalculates and goes into another sleep, waiting for another 5 seconds. This sleep part is blocking and holds up all the discovery requests for all resource types. Because of this, the version refreshes after the first 5 seconds, but the callback is unlocked after 15 seconds, causing that snapshot refreshed at this time.

### First solution 

We removed types that should be refreshed to from the list after the first reconciliation. I've changed it so that once we receive an ACK for a specific type on a specific stream, we then remove it from the list. This way, we continue refreshing until there is an ACK.

I think another option could be to sleep only for the specific type because currently, we block all discovery requests until the resources appear.

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2024-05-27 06:20 UTC, slonka commented
we shouldn't be holding up all types when only one fails

2024-05-28 15:30 UTC, jakubdyszkiewicz requested changes

2024-05-28 16:10 UTC, lukidzi commented
Test fails because it uses kuma 2.6.6 which also has this bug and needs backport

2024-05-29 09:38 UTC, jakubdyszkiewicz requested changes

2024-05-29 09:38 UTC, jakubdyszkiewicz commented on pkg/kds/v2/server/resource_retry_forcer.go
> +	if _, found := r.streamToDelay[streamID]; found {
you need lock to access this map

2024-05-29 14:29 UTC, jakubdyszkiewicz approved these changes

2024-05-29 14:30 UTC, merged