fix(k8s): relax validation on sectionName with ServiceMesh
kumahq/kuma pull request #11819
Opened 2024-10-21 18:38 UTC by Neyaz

## Motivation

According to https://github.com/kumahq/kuma/issues/11572 there's no real reason to have such validation.
However, I didn't get if this part from the issue `If one of the matching meshService doesn't have such a sectionName it should simply not match just like it's already the case for labels.`  already works in this way or it needs to be implemented.

## Implementation information

The change is pretty simple.

## Supporting documentation
None

2024-10-22 07:12 UTC, jakubdyszkiewicz submitted a review, later dismissed

2024-10-22 07:14 UTC, jakubdyszkiewicz commented
Hey, thanks for the contribution.

> However, I didn't get if this part from the issue If one of the matching meshService doesn't have such a sectionName it should simply not match just like it's already the case for labels. already works in this way or it needs to be implemented.

I believe it already works that way. @lobkovilya to confirm

2024-10-22 08:27 UTC, lobkovilya requested changes
Unfortunately, even though it looks like it's supported, method [resolveTargetRef](https://github.com/kumahq/kuma/blob/f153461bd6e33dad7004209969591827604b6732/pkg/plugins/policies/core/rules/resourcerules.go#L250) doesn't take SectionName into account. 

I added the following input file to `pkg/plugins/policies/core/rules/testdata/resourcerules`:
```yaml
# MeshTimeout with targetRef to the real MeshService resource
type: MeshTimeout
name: matched-for-rules-mt-1
mesh: mesh-1
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: MeshService
        labels:
          env: dev
        sectionName: httpport
      default:
        idleTimeout: 10s
        connectionTimeout: 11s
        http:
          requestTimeout: 12s
---
type: MeshService
name: backend-1
mesh: mesh-1
labels:
  env: dev
spec:
  selector:
    dataplaneTags:
      app: backend
  ports:
    - port: 80
      name: httpport
      targetPort: 80
      appProtocol: http
---
type: MeshService
name: backend-2
mesh: mesh-1
labels:
  env: dev
spec:
  selector:
    dataplaneTags:
      app: backend
  ports:
    - port: 80
      targetPort: 80
      appProtocol: http
---
type: MeshService
name: backend-3
mesh: mesh-1
labels:
  env: prod
spec:
  selector:
    dataplaneTags:
      app: backend
  ports:
    - port: 80
      targetPort: 80
      appProtocol: http
```
and the golden file is not correct.

2024-10-22 10:25 UTC, Neyaz commented
@jakubdyszkiewicz @lobkovilya Thank you for a review!

Am I correct in assuming that, in order to implement this, if `sectionName` is set, then in the code, instead of using [implicitSectionName](https://github.com/kumahq/kuma/blob/f153461bd6e33dad7004209969591827604b6732/pkg/plugins/policies/core/rules/resourcerules.go#L277), I should create a resolved policy rule like this
 ```
append(rv, &resolvedPolicyItem{resource: r, item: item, implicitSectionName: item.GetTargetRef().SectionName})
```
?

2024-10-22 10:32 UTC, Neyaz commented
@jakubdyszkiewicz @lobkovilya Thank you for a review!

> Unfortunately, even though it looks like it's supported, method [resolveTargetRef](https://github.com/kumahq/kuma/blob/f153461bd6e33dad7004209969591827604b6732/pkg/plugins/policies/core/rules/resourcerules.go#L250) doesn't take SectionName into account.

@lobkovilya I believe it should be handled by [sectionName](https://github.com/kumahq/kuma/blob/f153461bd6e33dad7004209969591827604b6732/pkg/plugins/policies/core/rules/resourcerules.go#L243) method. As I see, it should return refSectionName for every `resolvedPolicyItem` if `sectionName` is set.

2024-10-29 09:38 UTC, lobkovilya commented
TBH I think the problem is in `resolveTargetRef`, it never calls `sectionName()` method and operates only with `implicitSectionName` (should also take into account the explicit one)

2025-02-03 13:18 UTC, lahabana commented
@lobkovilya what's the path forward on this PR?

2025-02-04 09:10 UTC, lobkovilya commented
I added support for Labels with SectionName in https://github.com/kumahq/kuma/pull/12743, once it's merged this PR is good to go

2025-02-25 22:49 UTC, lahabana commented
@lobkovilya should we try to push this in 2.10?

2025-02-26 09:04 UTC, lobkovilya commented
Yes, I merged master, let me test if it works as expected

2025-02-26 13:39 UTC, lobkovilya approved these changes

2025-02-26 16:20 UTC, lukidzi approved these changes

2025-02-26 17:01 UTC, merged