fix(kumactl): mark valid-for as required for command kumactl generate dataplane-token
kumahq/kuma pull request #11849
Opened 2024-10-24 09:30 UTC by jijiechen

## Motivation

fixes https://github.com/kumahq/kuma/issues/11848

## Implementation information

Mark the option as required.

Includes a small fixes  that resolves https://github.com/kumahq/kuma/pull/11107#discussion_r1751419328

## Supporting documentation

fixes https://github.com/kumahq/kuma/issues/11848

2024-10-24 09:31 UTC, Automaat approved these changes

2024-10-24 09:33 UTC, michaelbeaumont approved these changes

2024-10-24 09:51 UTC, jakubdyszkiewicz requested changes
name should not be required. You should be able to generate dataplane proxy for kuma.io/service tag

2024-10-25 09:49 UTC, jakubdyszkiewicz approved these changes

2024-10-28 14:13 UTC, lahabana commented
@jijiechen can we merge?

2024-10-29 03:15 UTC, merged