chore(kuma-cp) rename 'kumactl generate dataplane-token' CLI arg
kumahq/kuma pull request #1206
Opened 2020-11-24 14:29 UTC by lobkovilya

Signed-off-by: Ilya Lobkov <ilya.lobkov@konghq.com>

### Summary

rename `--dataplane` to `--name`

2020-11-24 15:35 UTC, nickolaev commented on app/kumactl/cmd/generate/generate_dataplane_token.go
> +		dataplane string // Deprecated: remove in next major version of Kuma 1.1
We have to find a way to track these deprecations. Either we have a fixed tag, like `Deprecated:` or we track in a dedicated doc.

2020-11-24 15:36 UTC, nickolaev approved these changes

2020-11-24 15:36 UTC, jakubdyszkiewicz approved these changes

2020-11-24 15:37 UTC, jakubdyszkiewicz commented
Make sure to update docs

2020-11-25 09:23 UTC, nickolaev requested changes
Please provide a link to the updated docs in the PR descripton.

2020-11-26 14:50 UTC, lobkovilya commented
That's weird, I looked through all documentation, but it's already correct:
```
kumactl generate dataplane-token \
  --name dp-echo-1 \
  --mesh default \
  --tag kuma.io/service=backend,backend-admin > /tmp/kuma-dp-echo1-token
```

2020-11-26 14:53 UTC, nickolaev approved these changes

2020-11-26 14:54 UTC, merged