feat(deployments) Add affinity, pdb, and hpa support
kumahq/kuma pull request #1551
Opened 2021-02-10 19:22 UTC by coreywagehoft

### Summary
Affinity, PodDisruptionBudget, and HorizontalPodAutoscaler are necessary requirements in our organization for highly available deployments.  A service mesh is a critical component and should have support for these.

### Full changelog

- Adding support for affinity for the control plane and ingress pods.
- Added support for PodDisruptionBudget for the control plane and ingress.
- Added support for HorizontalPodAutoscaler to the ingress.

2021-02-10 19:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kumahq/kuma?pullRequest=1551) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kumahq/kuma?pullRequest=1551) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kumahq/kuma?pullRequest=1551) it.</sub>

2021-02-10 19:40 UTC, austince requested changes
This looks really great, thanks so much for the contribution! Just left a few nits and an idea for adding `antiAffinity` as well

2021-02-10 19:40 UTC, austince commented on deployments/charts/kuma/templates/ingress-pdb.yaml
> +  {{- end  }}
nit: prefer

```
{{- with .Values... }}
minAvailable: {{ . }}
{{- end }}

2021-02-10 19:40 UTC, austince commented on deployments/charts/kuma/values.yaml
> +      # -- Weather to enable a Pod Disruption Budget for the ingress pods
```suggestion
      # -- Whether to enable a Pod Disruption Budget for the ingress pods
```

2021-02-10 19:40 UTC, austince commented on deployments/charts/kuma/templates/cp-deployment.yaml
> +{{ toYaml .Values.controlPlane.affinity | indent 8 }}
nit: prefer `nindent`

2021-02-10 19:40 UTC, austince commented on deployments/charts/kuma/values.yaml
> +    # -- Weather to enable a Pod Disruption Budget for the control plane pods
```suggestion
    # -- Whether to enable a Pod Disruption Budget for the control plane pods
```

2021-02-10 19:40 UTC, austince commented on deployments/charts/kuma/values.yaml
> +  affinity: {}
Should we add `antiAffinity` options as well? That could be important in the High Availability use case as well.

2021-02-10 19:40 UTC, austince commented on deployments/charts/kuma/Chart.yaml
> +appVersion: 1.0.8
Can you revert this one? We usually do version bumps during the release process.

2021-02-10 19:43 UTC, austince commented
Also, as a possible extension, could also add some end to end tests here: https://github.com/kumahq/kuma/blob/master/test/e2e/helm/kuma_helm_deploy_autoscaling_test.go

2021-02-17 21:58 UTC, subnetmarco commented
What is the status on this PR @coreywagehoft @austince @nickolaev ?

2021-02-17 22:15 UTC, austince commented on deployments/charts/kuma/values.yaml
> +  affinity: {}
Oops, re-reading I realize this is supported as a nested field. Sorry!

2021-02-17 22:16 UTC, austince commented
> What is the status on this PR @coreywagehoft @austince @nickolaev ?

I think just a few nits at this point. I think the e2e tests are optional and could go in now depending on how @coreywagehoft feels about the nits.

2021-02-17 22:32 UTC, coreywagehoft commented
I need to close this PR and submit a new one using my personal computer and sign the commit with my personal email address so I can sign the CLA.  I will however take into account the suggested changes when I open the new PR.

Apologies for the delay.

2021-02-17 22:32 UTC, closed without merging

2021-02-17 22:33 UTC, austince commented
> Apologies for the delay.

No worries, thanks for the update @coreywagehoft