feat(kuma-cp) add k8s apiServer passthrough bypass
kumahq/kuma pull request #1850
Opened 2021-04-19 13:12 UTC by bartsmykla

This is the feature which allows communication with k8s api server when mesh has `passthrough` set to `false`

2021-04-20 10:08 UTC, jakubdyszkiewicz requested changes
Please add tests. Unit tests at least, but I'd feel safer if we have E2E for this (should be simple to do, we already have test for passthrough false)

2021-04-20 10:08 UTC, jakubdyszkiewicz commented on pkg/plugins/bootstrap/k8s/hooks/api_server_bypass.go
> +	OriginApiServerBypass            = "api_server_bypass"
nit: camelCase?

2021-04-27 06:17 UTC, bartsmykla commented on pkg/plugins/bootstrap/k8s/hooks/api_server_bypass.go
> +package hooks
Addressed

2021-04-27 06:17 UTC, bartsmykla commented on pkg/plugins/bootstrap/k8s/hooks/api_server_bypass.go
> +	OriginApiServerBypass            = "api_server_bypass"
addressed

2021-04-27 10:37 UTC, bartsmykla commented
@jakubdyszkiewicz I have added e2e test. Could you check again please? :-)

2021-04-27 10:59 UTC, jakubdyszkiewicz approved these changes
please coordinate with Nikolay's tests refactor

2021-04-27 10:59 UTC, jakubdyszkiewicz commented on test/e2e/k8s_api_bybass/k8s_api_bypass_test.go
> +	}
it should work with V2

2021-04-27 11:01 UTC, bartsmykla commented on test/e2e/k8s_api_bybass/k8s_api_bypass_test.go
> +	}
removed

2021-04-28 15:21 UTC, merged