chore(*) improve resource manager initialization readability
kumahq/kuma pull request #2316
Opened 2021-07-06 08:58 UTC by jpeach

### Summary

This refactoring is a bit gratuitous, so I'm not that concerned if we don't want to merge it :-)

I was reading the resource manager setup and it was confusing how the type map was still being initialized after already being "consumed" by customizable resource manager.

### Full changelog

N/A

### Issues resolved

N/A

### Documentation

N/A

### Testing

- [x] Unit tests
- [x] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

2021-07-06 09:13 UTC, lobkovilya approved these changes
This makes sense and for sure improves readability, so I'm not against merging this one

2021-07-06 09:13 UTC, lobkovilya commented on pkg/core/resources/manager/customizable_manager.go
> +		panic(fmt.Sprintf("resource type %q is already customized", resourceType))
I'd better panicked with `error` rather than `string`

2021-07-06 10:12 UTC, jakubdyszkiewicz requested changes
My bad, I introduced Customize method, I should have refactored the rest.

👍

2021-07-07 23:12 UTC, jpeach commented on pkg/core/resources/manager/customizable_manager.go
> +		panic(fmt.Sprintf("resource type %q is already customized", resourceType))
I did (1)

2021-07-09 12:48 UTC, jakubdyszkiewicz approved these changes

2021-07-12 01:19 UTC, merged