fix(kuma-cp) subscription finalizer, rev 2
kumahq/kuma pull request #2526
Opened 2021-08-09 11:09 UTC by lobkovilya

### Summary

Based on https://github.com/kumahq/kuma/pull/2444, e2e tests and subscription refactoring were taken from there, but the algorithm is different. 

After the discussion with @jpeach we came up with the new algorithm:
* Every N/2 mins StatusSink increments `generation` counter. 
* Every N mins Finalizer checks that `generation` counter was changed.
* If counter didn't change after N minutes, Finalizer considers it as disconnected and sets DisconnectTime

The current algorithm requires 2 times fewer UPDATE operations on the storage. 

### Full changelog

* add subscriptionFinalizer
* enable resilient tests
* new `idleTimeout` property for kuma-cp config

### Issues resolved

Fix https://github.com/kumahq/kuma/issues/2320

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [X] Unit tests
- [X] E2E tests
- [X] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [ ] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

2021-08-11 12:46 UTC, jakubdyszkiewicz commented on api/mesh/v1alpha1/dataplane_insight_helpers.go
> +// todo(lobkovilya): delete GetLatestSubscription, use GetLastSubscription instead
Will this be done in this PR or separate? If separate, do we have a issue / card for it?

2021-08-11 12:46 UTC, jakubdyszkiewicz commented on pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
>      enabled: true # ENV: KUMA_METRICS_ZONE_ENABLED
I'm thinking... now we rely on Insights to provide a stable product. Should we remove an option to disable insights?

2021-08-12 09:17 UTC, jpeach requested changes
> Reviewed 19 of 29 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kumahq/kuma/2526)* status: 21 of 30 files reviewed, 17 unresolved discussions (waiting on @lobkovilya)

___
*[api/helpers/insights.go, line 1 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgng0IYB1-6l_sKPH1J:-Mgng0IZ84ALKQvx-bnp:bstpl20) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/helpers/insights.go#L1)):*
> ```Go
> package helpers
> ```

Suggest that we call this package `generic` or `interface`. `generic.Insight` reads nicely IMHO.
___
*[api/mesh/v1alpha1/dataplane_insight.proto, line 74 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgngZjc5yY6T_HEGe68:-MgngZjc5yY6T_HEGe69:bi945q9) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/dataplane_insight.proto#L74)):*
> ```protobuf
> 
>   // Generation is an integer number which is periodically increased by the
>   // status sink
> ```

Nit: end sentence with a full-stop. Here and elsewhere.

https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
___
*[api/mesh/v1alpha1/dataplane_insight_helpers.go, line 9 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnhY7hA8UHmq9P1sDg:-MgnhY7hA8UHmq9P1sDh:b-eb8kcr) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/dataplane_insight_helpers.go#L9)):*
> ```Go
> 	"google.golang.org/protobuf/types/known/timestamppb"
> 
> 	"github.com/kumahq/kuma/api/helpers"
> ```

Since you already imported this package, WDYT about adding type assertions for the insight and subscription types?
___
*[api/mesh/v1alpha1/dataplane_insight_helpers.go, line 102 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnhEA28OHdeKcrX-o4:-MgnhEA37pfQ6S0SyWUt:bswqsa1) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/dataplane_insight_helpers.go#L102)):*
> ```Go
> }
> 
> // todo(lobkovilya): delete GetLatestSubscription, use GetLastSubscription instead
> ```

File an issue for this TODO?
___
*[api/mesh/v1alpha1/zone_ingress_insight_helpers.go, line 8 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgni65eBBPdSXgja0HY:-Mgni65eBBPdSXgja0HZ:bcnvsok) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/zone_ingress_insight_helpers.go#L8)):*
> ```Go
> 	"google.golang.org/protobuf/types/known/timestamppb"
> 
> 	"github.com/kumahq/kuma/api/helpers"
> ```

Same suggestion to add type assertions.
___
*[api/mesh/v1alpha1/zone_ingress_insight_helpers.go, line 24 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgniIIk7g_s-a-HGGuQ:-MgniIIk7g_s-a-HGGuR:b-ok9r0w) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/zone_ingress_insight_helpers.go#L24)):*
> ```Go
> 		return
> 	}
> 	discoverySubscription, ok := s.(*DiscoverySubscription)
> ```

This should never happen, right? Can we just let this panic?
___
*[pkg/gc/collector_test.go, line 66 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgnkcq20_5xOPYTfG86:-Mgnkcq20_5xOPYTfG87:bofpik9) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/collector_test.go#L66)):*
> ```Go
> 		Expect(err).ToNot(HaveOccurred())
> 		mtxNow.Lock()
> 		core.Now = func() time.Time {
> ```

We should reset `core.Now` in an `AfterEach`.
___
*[pkg/gc/collector_test.go, line 69 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnkppiEfAGocpiAMkz:-MgnkppiEfAGocpiAMl-:b-7w2byp) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/collector_test.go#L69)):*
> ```Go
> 			return now
> 		}
> 		mtxNow.Unlock()
> ```

Why do we need the mutex here?
___
*[pkg/gc/components.go, line 66 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnmKb63ZBMoU-ml1Fk:-MgnmKb63ZBMoU-ml1Fl:b-nytpim) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/components.go#L66)):*
> ```Go
> 		}
> 	default:
> 		return errors.Errorf("unknown Kuma CP mode %v", rt.Config().Mode)
> ```

nit: should use `%s` here
___
*[pkg/gc/finalizer.go, line 35 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnsfX58Vl09G2mM3hX:-MgnsfXIBXVjbBtVzOga:bfv644z) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L35)):*
> ```Go
> // 4. DPP status is Online whereas it should be Offline
> 
> type descriptor struct {
> ```

Suggest this would be clearer if we called it `subscription`.
___
*[pkg/gc/finalizer.go, line 40 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgntP7Z3A5rirvjzsNO:-MgntP7_8nu1Wif8H-2F:brczhnw) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L40)):*
> ```Go
> }
> 
> type insightMap map[core_model.ResourceKey]*descriptor
> ```

Do we need a pointer here, or just use a value directly.
___
*[pkg/gc/finalizer.go, line 54 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgnn8wH-u-HQhvbxah5:-Mgnn8wH-u-HQhvbxah6:b-kgr7ey) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L54)):*
> ```Go
> 	insights := insightsByType{}
> 	for _, typ := range types {
> 		if err := validateType(typ); err != nil {
> ```

Suggest that we rename `validateType` for clarity and just make it return `bool`:

```Go
if !isInsightType(typ) {
    return fmt.Errorf("%q type is not an Insight", typ)
}
```
___
*[pkg/gc/finalizer.go, line 90 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnoiNwDilYlhQGnumk:-MgnoiO5BfosJjC1GcaT:b34jith) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L90)):*
> ```Go
> func (f *subscriptionFinalizer) checkGeneration(typ core_model.ResourceType) error {
> 	// get all the insights for provided type
> 	ctx := context.Background()
> ```

Nit: this is only used once, let's just inline it.
___
*[pkg/gc/finalizer.go, line 97 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnvR2nEGHeKppcPzOR:-MgnvR2nEGHeKppcPzOS:b-314g38) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L97)):*
> ```Go
> 
> 	// delete items from the map that don't exist in the upstream
> 	f.upstreamSync(insights)
> ```

Rename `upstreamSync`to more obviously be named after what it is doing.  Maybe `removeDeletedInsights`?
___
*[pkg/gc/finalizer.go, line 120 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgnu1OZCesBuQFJGH3z:-Mgnu1OZCesBuQFJGH4-:btvh02q) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L120)):*
> ```Go
> 		}
> 
> 		log.V(1).Info("mark subscription as disconnected")
> ```

Log the subscription ID and generation here?
___
*[pkg/gc/finalizer.go, line 129 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnuQZ7-mc68XFMe1Ap:-MgnuQZ7-mc68XFMe1Aq:b50p785) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L129)):*
> ```Go
> 		if err != nil {
> 			log.Error(err, "unable to finalize subscription")
> 		}
> ```

Return the error here? If we return the error then we will also keep the map entry, which means that we will come back and retry.
___
*[pkg/gc/finalizer_test.go, line 41 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnxPUB3W4wvgBlvdK6:-MgnxPUJ2Dru_9Y3XIXM:bbk4grh) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer_test.go#L41)):*
> ```Go
> 			mtxNow.RLock()
> 			_ = finalizer.Start(stop)
> 			mtxNow.RUnlock()
> ```

Not sure that we have to lock this over the whole run time. The `BeforeEach` should always complete before we run anything, right?


<!-- Sent from Reviewable.io -->

2021-08-12 14:15 UTC, lobkovilya reviewed
> *[Reviewable](https://reviewable.io/reviews/kumahq/kuma/2526)* status: 21 of 30 files reviewed, 18 unresolved discussions (waiting on @jakubdyszkiewicz, @jpeach, and @lobkovilya)

___
*[api/helpers/insights.go, line 1 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgng0IYB1-6l_sKPH1J:-Mgu6Eno5VEOeR9D-uhg:b-896fix) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/helpers/insights.go#L1)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Suggest that we call this package `generic` or `interface`. `generic.Insight` reads nicely IMHO.
</blockquote></details>

Done.
___
*[api/mesh/v1alpha1/dataplane_insight.proto, line 74 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgngZjc5yY6T_HEGe68:-Mgu6Nan6j9gARcaEG5f:bgkll8c) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/dataplane_insight.proto#L74)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Nit: end sentence with a full-stop. Here and elsewhere.

https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
</blockquote></details>

because of the approach, proposed by @jakubdyszkiewicz, we can avoid extending API at all
___
*[api/mesh/v1alpha1/dataplane_insight.pb.go, line 112 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgmyqYoZILf9j-NZN0G-r2-112:-Mgu6h875M6nxpCZ6hPk:b-qlbomd) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/dataplane_insight.pb.go#L112)):*
<details><summary><i>Previously, jakubdyszkiewicz (Jakub Dyszkiewicz) wrote…</i></summary><blockquote>

would it be possible to use Version from ResourceMeta instead?
</blockquote></details>

This is a really good idea, done.
___
*[api/mesh/v1alpha1/dataplane_insight_helpers.go, line 102 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgmyqYoZILf9j-NZN0I-r2-102:-MguIC38Ccb41r51yR03:b-camwww) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/dataplane_insight_helpers.go#L102)):*
<details><summary><i>Previously, jakubdyszkiewicz (Jakub Dyszkiewicz) wrote…</i></summary><blockquote>

Will this be done in this PR or separate? If separate, do we have a issue / card for it?
</blockquote></details>

Done https://github.com/kumahq/kuma/issues/2557
___
*[api/mesh/v1alpha1/dataplane_insight_helpers.go, line 102 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnhEA28OHdeKcrX-o4:-MguID2FEHV8LqUePmnY:b-camwww) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/dataplane_insight_helpers.go#L102)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

File an issue for this TODO?
</blockquote></details>

Done https://github.com/kumahq/kuma/issues/2557
___
*[api/mesh/v1alpha1/zone_ingress_insight_helpers.go, line 24 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgniIIk7g_s-a-HGGuQ:-MguIPEJ-66T06YFNJ2a:bw3c7a3) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/zone_ingress_insight_helpers.go#L24)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

This should never happen, right? Can we just let this panic?
</blockquote></details>

If a developer makes a mistake and passes the wrong subscription type to the `UpdateSubscription`, will this panic immediately? 
I can imagine the code that operates with subscriptions in a generic way (like finalizer.go) and may cause not an immediate panic, but panic later in production. So I'd better avoid panic here, maybe log some error? 
___
*[pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, line 277 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgmyqYoZILf9j-NZN0Q-r2-277:-Mgu70VS7jXHVe2qth-R:b-rp38te) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L277)):*
<details><summary><i>Previously, jakubdyszkiewicz (Jakub Dyszkiewicz) wrote…</i></summary><blockquote>

I'm thinking... now we rely on Insights to provide a stable product. Should we remove an option to disable insights?
</blockquote></details>

If you disable Insights you won't see correct statuses in GUI, that's how it worked before this PR. But if we want to remove `enabled` option, I can do it
___
*[pkg/gc/collector_test.go, line 66 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgnkcq20_5xOPYTfG86:-MguLS5wEhDknVxcxVUn:b-896fix) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/collector_test.go#L66)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

We should reset `core.Now` in an `AfterEach`.
</blockquote></details>

Done.
___
*[pkg/gc/collector_test.go, line 69 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnkppiEfAGocpiAMkz:-MguLTGk2loEYiuras0d:bal0enx) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/collector_test.go#L69)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Why do we need the mutex here?
</blockquote></details>

Added the comment:
```go
// The problem is SubscriptionFinalizer in the same package uses core.Now
// variable to set DisconnectTime when finalizes subscription.
// Test in the current file replaces core.Now for testing purposes. When running
// the whole suite with `-race` flag it constantly fails with `WARNING: DATA RACE`.
// In order to avoid that we protect core.Now with mtxNow mutex in the scope
// of this gc_test package.
```
___
*[pkg/gc/finalizer.go, line 35 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnsfX58Vl09G2mM3hX:-Mgu87SC1bc2kPraoFkn:b-vk1sw9) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L35)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Suggest this would be clearer if we called it `subscription`.
</blockquote></details>

now it's just `version`, so got rid of this struct
___
*[pkg/gc/finalizer.go, line 40 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgntP7Z3A5rirvjzsNO:-Mgu8UXB8Lx1nuRQJysJ:bb7od0r) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L40)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Do we need a pointer here, or just use a value directly.
</blockquote></details>

same
___
*[pkg/gc/finalizer.go, line 54 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgnn8wH-u-HQhvbxah5:-Mgu9V5O9DhVeDhVaoRe:b-5m1se3) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L54)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Suggest that we rename `validateType` for clarity and just make it return `bool`:

```Go
if !isInsightType(typ) {
    return fmt.Errorf("%q type is not an Insight", typ)
}
```
</blockquote></details>

Done. Now `isInsightType` could panic if `obj, err := registry.Global().NewObject(typ)` fails, but I think it's acceptable
___
*[pkg/gc/finalizer.go, line 97 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnvR2nEGHeKppcPzOR:-Mgu9szq-l9V_UNF4oah:b-896fix) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/gc/finalizer.go#L97)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Rename `upstreamSync`to more obviously be named after what it is doing.  Maybe `removeDeletedInsights`?
</blockquote></details>

Done.
___
*[pkg/gc/finalizer.go, line 120 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgnu1OZCesBuQFJGH3z:-MguA541EwuJLlLyg_yv:b-5jifet) ([raw file](https://github.com/kum [...]

2021-08-12 22:13 UTC, jpeach reviewed
> Reviewed 3 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kumahq/kuma/2526)* status: 10 of 30 files reviewed, 9 unresolved discussions (waiting on @jakubdyszkiewicz, @jpeach, and @lobkovilya)



<!-- Sent from Reviewable.io -->

2021-08-13 00:06 UTC, jpeach requested changes
> Reviewed 8 of 29 files at r1, 12 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kumahq/kuma/2526)* status: 29 of 30 files reviewed, 11 unresolved discussions (waiting on @jakubdyszkiewicz, @jpeach, and @lobkovilya)

___
*[api/mesh/v1alpha1/zone_ingress_insight_helpers.go, line 24 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgniIIk7g_s-a-HGGuQ:-Mgwc9bKE3aoMyWJUS-x:b-twki11) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/zone_ingress_insight_helpers.go#L24)):*
<details><summary><i>Previously, lobkovilya (Ilya Lobkov) wrote…</i></summary><blockquote>

If a developer makes a mistake and passes the wrong subscription type to the `UpdateSubscription`, will this panic immediately? 
I can imagine the code that operates with subscriptions in a generic way (like finalizer.go) and may cause not an immediate panic, but panic later in production. So I'd better avoid panic here, maybe log some error? 
</blockquote></details>

Then can we propagate an error out of `UpdateSubscription`? That can bubble up through the upsert and be handled in the finalizer.
___
*[pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, line 277 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgmyqYoZILf9j-NZN0Q-r2-277:-MgwcwDrCyWw6jVC4aaF:bdee6ya) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L277)):*
<details><summary><i>Previously, lobkovilya (Ilya Lobkov) wrote…</i></summary><blockquote>

If you disable Insights you won't see correct statuses in GUI, that's how it worked before this PR. But if we want to remove `enabled` option, I can do it
</blockquote></details>

Shall we discuss this in a separate issue?
___
*[pkg/gc/finalizer.go, line 116 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgwa0MJ6287hoiqBfkX:-Mgwa0MJ6287hoiqBfkY:b-hc7qg0) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/gc/finalizer.go#L116)):*
> ```Go
> 
> 		upsertInsight, _ := registry.Global().NewObject(typ)
> 		err := manager.Upsert(f.rm, core_model.MetaToResourceKey(item.GetMeta()), upsertInsight, func(_ core_model.Resource) {
> ```

You already have a local variable `key` that you can use here.
___
*[pkg/gc/finalizer.go, line 117 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwaZkQ8roCHyEVvJUJ:-MgwaZkQ8roCHyEVvJUK:b-mi59ve) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/gc/finalizer.go#L117)):*
> ```Go
> 		upsertInsight, _ := registry.Global().NewObject(typ)
> 		err := manager.Upsert(f.rm, core_model.MetaToResourceKey(item.GetMeta()), upsertInsight, func(_ core_model.Resource) {
> 			upsertInsight.GetSpec().(generic.Insight).UpdateSubscription(insight.GetLastSubscription())
> ```

Here, aren't you supposed to update the parameter passed to the callback func?
___
*[pkg/kds/server/status_sink.go, line 60 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwmkkeBtiki3J-bW71:-MgwmkkeBtiki3J-bW72:blbusix) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/kds/server/status_sink.go#L60)):*
> ```Go
> 
> 	var lastStoredState *system_proto.KDSSubscription
> 	forceUpdate := false
> ```

Move this into `flush()` and drop the reset.
___
*[pkg/xds/server/callbacks/dataplane_status_sink.go, line 65 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwlI4iBujjRgyGaRre:-MgwlI4j3slJQuUtEWBl:b-6ll1fb) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/xds/server/callbacks/dataplane_status_sink.go#L65)):*
> ```Go
> 
> 	var lastStoredState *mesh_proto.DiscoverySubscription
> 	forceUpdate := false
> ```

If you make this local to `flush()` then you don't need to reset it.
___
*[pkg/xds/server/callbacks/dataplane_status_sink.go, line 75 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwlS9oBz5yqG5ynwg6:-MgwlS9oBz5yqG5ynwg7:bi9stpv) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/xds/server/callbacks/dataplane_status_sink.go#L75)):*
> ```Go
> 		}
> 
> 		if proto.Equal(currentState, lastStoredState) && !forceUpdate {
> ```

I'm am pretty sure that Kubernetes does not guarantee to increment the resource version if you do a no-op write.

https://github.com/kubernetes/kubernetes/issues/67541


<!-- Sent from Reviewable.io -->

2021-08-13 18:06 UTC, lobkovilya reviewed
> *[Reviewable](https://reviewable.io/reviews/kumahq/kuma/2526)* status: 29 of 30 files reviewed, 11 unresolved discussions (waiting on @jakubdyszkiewicz and @jpeach)

___
*[api/mesh/v1alpha1/dataplane_insight_helpers.go, line 9 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgnhY7hA8UHmq9P1sDg:-MgyF9sT-1NFisbsSeKK:b-896fix) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/dataplane_insight_helpers.go#L9)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Since you already imported this package, WDYT about adding type assertions for the insight and subscription types?
</blockquote></details>

Done.
___
*[api/mesh/v1alpha1/zone_ingress_insight_helpers.go, line 8 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgni65eBBPdSXgja0HY:-MgyF8UrDHzrHLkI7nnO:b-896fix) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/zone_ingress_insight_helpers.go#L8)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Same suggestion to add type assertions.
</blockquote></details>

Done.
___
*[api/mesh/v1alpha1/zone_ingress_insight_helpers.go, line 24 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgniIIk7g_s-a-HGGuQ:-Mgz6vIPDhXWy9dQ_FDB:b-896fix) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/api/mesh/v1alpha1/zone_ingress_insight_helpers.go#L24)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Then can we propagate an error out of `UpdateSubscription`? That can bubble up through the upsert and be handled in the finalizer.
</blockquote></details>

Done.
___
*[pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, line 277 at r2](https://reviewable.io/reviews/kumahq/kuma/2526#-MgmyqYoZILf9j-NZN0Q-r2-277:-Mh-gOwJ7YUTkDEFi-eI:b-er8oa9) ([raw file](https://github.com/kumahq/kuma/blob/3d1dcb513647ad3b30da75d28be1d815185180fb/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L277)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Shall we discuss this in a separate issue?
</blockquote></details>

Yep, done https://github.com/kumahq/kuma/issues/2565
___
*[pkg/gc/finalizer.go, line 116 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-Mgwa0MJ6287hoiqBfkX:-MgzAy_77ty2fsunFHZS:b-896fix) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/gc/finalizer.go#L116)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

You already have a local variable `key` that you can use here.
</blockquote></details>

Done.
___
*[pkg/gc/finalizer.go, line 117 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwaZkQ8roCHyEVvJUJ:-MgzB_nD5T8Qek1R7IPl:bqyj3x) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/gc/finalizer.go#L117)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Here, aren't you supposed to update the parameter passed to the callback func?
</blockquote></details>

That doesn't matter, the variable is the same
___
*[pkg/kds/server/status_sink.go, line 60 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwmkkeBtiki3J-bW71:-MgzFpLu72ssKeTp_p8X:bpfugy5) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/kds/server/status_sink.go#L60)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

Move this into `flush()` and drop the reset.
</blockquote></details>

Right, thanks!
___
*[pkg/xds/server/callbacks/dataplane_status_sink.go, line 65 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwlI4iBujjRgyGaRre:-MgzFsEQ6Jsthl0Yv-CS:b-896fix) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/xds/server/callbacks/dataplane_status_sink.go#L65)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

If you make this local to `flush()` then you don't need to reset it.
</blockquote></details>

Done.
___
*[pkg/xds/server/callbacks/dataplane_status_sink.go, line 75 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwlS9oBz5yqG5ynwg6:-Mh-fBe68XHpKHX-n559:b-r937sv) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/xds/server/callbacks/dataplane_status_sink.go#L75)):*
<details><summary><i>Previously, jpeach (James Peach) wrote…</i></summary><blockquote>

I'm am pretty sure that Kubernetes does not guarantee to increment the resource version if you do a no-op write.

https://github.com/kubernetes/kubernetes/issues/67541
</blockquote></details>

Yes, that's true, revert last changes and restore 'generation' field


<!-- Sent from Reviewable.io -->

2021-08-16 06:31 UTC, jpeach requested changes
> Reviewed 7 of 14 files at r4, 20 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kumahq/kuma/2526)* status: 36 of 37 files reviewed, 4 unresolved discussions (waiting on @jakubdyszkiewicz, @jpeach, and @lobkovilya)

___
*[pkg/gc/finalizer.go, line 117 at r3](https://reviewable.io/reviews/kumahq/kuma/2526#-MgwaZkQ8roCHyEVvJUJ:-MhCd5LBC7elw9lRFu_w:b-klv0ld) ([raw file](https://github.com/kumahq/kuma/blob/d2094a3826526ec47754bb6d00a2409699b61d14/pkg/gc/finalizer.go#L117)):*
<details><summary><i>Previously, lobkovilya (Ilya Lobkov) wrote…</i></summary><blockquote>

That doesn't matter, the variable is the same
</blockquote></details>

Is there a guarantee that it can't be concurrently written by the sink?


<!-- Sent from Reviewable.io -->

2021-08-16 07:49 UTC, jpeach approved these changes
> *[Reviewable](https://reviewable.io/reviews/kumahq/kuma/2526)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @jakubdyszkiewicz and @jpeach)



<!-- Sent from Reviewable.io -->

2021-08-16 10:00 UTC, merged

2021-08-16 23:11 UTC, jpeach commented
@lobkovilya No backporting this one?