Adds support for specifying specific IP for cloud provider load balan…
kumahq/kuma pull request #2779
Opened 2021-09-15 08:53 UTC by jamesdbloom

### Summary

Adds support for specifying specific IP for cloud provider load balancers, see: https://kubernetes.io/docs/concepts/services-networking/service/\#loadbalancer or https://docs.microsoft.com/en-us/azure/aks/static-ip\#create-a-service-using-the-static-ip-address

### Full changelog

* added ability to configure loadBalancerIP to for control plane service

### Documentation

- documented in deployments/charts/kuma/values.yaml

### Testing

- [X] Manual testing on Kubernetes 

### Backwards compatibility

- [X] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

2021-09-15 08:53 UTC, jamesdbloom commented
This PR replaces #2622

2021-09-16 07:39 UTC, lahabana approved these changes

2021-09-16 07:42 UTC, lahabana requested changes
Could you please sign your commit?

See: https://github.com/kumahq/kuma/blob/master/CONTRIBUTING.md#sign-your-work

Also in the other PR you mentioned a possible issue with exposing multiple ports. Why is this not an issue anymore?

2021-09-16 13:46 UTC, jamesdbloom commented
@lahabana 

I did sign the commit with the `-s` flag no `git commit` and github is showing it as verified, do I also need to add `Signed-off-by: James D Bloom <733179+jamesdbloom@users.noreply.github.com>`

I removed the part of the PR that made no sense due to multiple different protocols so it is no longer relavent.

2021-09-16 14:19 UTC, lahabana commented
Yes you need the Signed-off-by bit in the commit message.

2021-09-17 11:58 UTC, jamesdbloom commented
@lahabana I've added the Signed-off-by bit now

2021-09-20 17:09 UTC, lahabana approved these changes

2021-09-20 17:09 UTC, lahabana commented
Thx for the contrib!

2021-09-20 17:10 UTC, merged