Feat/tracing added support for https tracing endpoint
kumahq/kuma pull request #3057
Opened 2021-11-01 14:15 UTC by sudeeptoroy

### Summary

added support for https tracing endpoints 

### Issues resolved

Fix #2613 

### Testing

- [ *] Unit tests

### Backwards compatibility

- [* ] `backport-to-stable`

2021-11-02 08:55 UTC, lahabana requested changes
LGTM thank you for the contribution!

2021-11-02 08:55 UTC, lahabana commented on pkg/xds/envoy/clusters/v3/dns_cluster_configurer_test.go
> +		isHttp      bool
Is this meant to be https ?

2021-11-02 18:15 UTC, sudeeptoroy commented on pkg/xds/envoy/clusters/v3/dns_cluster_configurer_test.go
> +		isHttp      bool
yes, you are right.. i will fix it.

2021-11-03 09:01 UTC, lahabana approved these changes
LGTM!

2021-11-03 17:10 UTC, merged