feat(gateway): validate GatewayInstance resources
kumahq/kuma pull request #3564
Opened 2021-12-16 14:59 UTC by michaelbeaumont

### Summary

Closes #3502

2021-12-19 22:22 UTC, jpeach requested changes

2021-12-20 09:18 UTC, michaelbeaumont commented on pkg/core/resources/apis/mesh/validators.go
> +func ValidateTags(tags map[string]string) validators.ValidationError {
https://github.com/kumahq/kuma/pull/3580

2021-12-20 14:59 UTC, michaelbeaumont commented on pkg/core/resources/apis/mesh/zone_ingress_validator.go
> +		err.AddErrorAt(p.Field("tags"), ValidateTags(availableService.GetTags()))
fixed in `master`

2021-12-20 14:59 UTC, michaelbeaumont commented on pkg/core/resources/apis/mesh/validators.go
> +			result.AddViolationAt(validators.RootedAt("tags").Key(name), `tag value cannot be empty`)
fixed in `master` by #3580

2021-12-20 14:59 UTC, michaelbeaumont commented on pkg/core/resources/apis/mesh/validators.go
> +			result.AddViolationAt(validators.RootedAt("tags").Key(name), `tag value cannot be empty`)
fixed in `master` by #3580

2021-12-21 01:17 UTC, jpeach approved these changes

2021-12-21 01:17 UTC, jpeach commented on pkg/plugins/runtime/k8s/webhooks/gateway_instance_validator.go
> +	}
IIUC can just use `Decode` here. I'm not really sure why other validators want to validate both the old and the new objects - unless there's a possibility of making an invalid state transition, I would expect that only the new object matters.

2021-12-21 09:02 UTC, merged