feat(gateway): initial support for GatewayStatus.Listeners
kumahq/kuma pull request #3609
Opened 2021-12-22 12:09 UTC by michaelbeaumont

### Summary

Not every `Condition` /`Reason` for the `Condition`s is covered yet.

2022-01-11 04:00 UTC, jpeach requested changes
FWIW it would be helpful to include more detail about the change in the commit message (mirrored in the PR) ... it wasn't clear to me that this PR addresses refpolicy for secrets until I went back and looked at the diff for each commit. It was very hard to tell from the aggregated diff because of the code movement.

2022-01-11 09:53 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +			ref := policy.PolicyReferenceSecret(policy.FromGatewayIn(gateway.Namespace), *certRef)
Yeah, that's the result of changing the API and code too many times. Fixed the NPE in a separate PR.

2022-01-11 10:05 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +			listenerConditions[l.Name] = append(listenerConditions[l.Name], resolvedCondition...)
Of course :man_facepalming:

2022-01-11 10:14 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +						Message: fmt.Sprintf("reference to %s %s/%s not permitted by any ReferencePolicy", targetGK.String(), ref.ToNamespace(), certRef.Name),
> nit: if you take the name and namespace from the same object it is more obvious

the issue is that `certRef.Namespace` may be nil, that's why I introduced `PolicyReference`. I'll expose the other fields there.

2022-01-11 10:15 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy.go
> +var gatewayKind = gatewayapi.Kind("Gateway")
I think I prefer to leave them out. This makes it feel less like I'm referring to types with strings at least, and makes it more likely they'll be reused.

2022-01-11 10:17 UTC, jpeach commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +type ListenerConditions map[gatewayapi.SectionName][]kube_meta.Condition
https://github.com/kubernetes-sigs/gateway-api/issues/984

2022-01-11 10:17 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy.go
> +var gatewayKind = gatewayapi.Kind("Gateway")
Actually this package is so small, you're right

2022-01-11 10:28 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +						Message: fmt.Sprintf("reference to %s %s/%s not permitted by any ReferencePolicy", targetGK.String(), ref.ToNamespace(), certRef.Name),
done, also improved the error code

2022-01-11 10:33 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +			ref := policy.PolicyReferenceSecret(policy.FromGatewayIn(gateway.Namespace), *certRef)
also improved the caller code

2022-01-11 10:37 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +type ListenerConditions map[gatewayapi.SectionName][]kube_meta.Condition
Added to https://github.com/kumahq/kuma/issues/3617

2022-01-11 10:54 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
> +	if len(gateway.Status.Addresses) == 0 {
I've got a PR ready for after this is merged

2022-01-11 11:03 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +						Message: fmt.Sprintf("reference to %s %s/%s not permitted by any ReferencePolicy", targetGK.String(), ref.ToNamespace(), certRef.Name),
https://github.com/kumahq/kuma/pull/3693

2022-01-11 11:08 UTC, michaelbeaumont commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
> +func gatewayAddresses(gateway *gatewayapi.Gateway, instance *mesh_k8s.GatewayInstance) []gatewayapi.GatewayAddress {
See below, doing in separate PR.

2022-01-12 00:07 UTC, jpeach commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
> +type ListenerConditions map[gatewayapi.SectionName][]kube_meta.Condition
I was totally wrong about this - the section name is guaranteed to be unique and there are API server validations to enforce that.

2022-01-12 05:34 UTC, jpeach approved these changes

2022-01-12 05:34 UTC, jpeach commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
> +						Message: fmt.Sprintf("backend reference references a non-existent Service %s", namespacedName.String()),
Nit: prefer %q for unambiguously formatting names

2022-01-12 05:34 UTC, jpeach commented on pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
> +				Message: fmt.Sprintf("reference to %s %s not permitted by any ReferencePolicy", gk, namespacedName),
Nit: I wanna suggest using %q for the NamespacedName, but it's borderline, so if you don't agree, don't worry about it :)

2022-01-12 07:54 UTC, merged