ci: check shell scripts with shellcheck
kumahq/kuma pull request #3785
Opened 2022-02-01 16:56 UTC by michaelbeaumont

### Summary

Also add install targets and fix lint errors.

2022-02-01 17:01 UTC, parkanzky approved these changes

2022-02-02 11:24 UTC, jakubdyszkiewicz requested changes
It does not work for MacOS :(

```
❯❯❯ make shellcheck
find -name "*.sh" -not -path "./.git/*" -exec shellcheck -P SCRIPTDIR -x {} +
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
make: *** [shellcheck] Error 1
```

2022-02-02 11:31 UTC, michaelbeaumont commented
> It does not work for MacOS :(

Yeah, I was worried this might happen. Unfortunately `shellcheck` has the ["have everyone solve the same problem over and over again so we don't need to put in any effort" philosophy](https://github.com/koalaman/shellcheck/issues/143#issuecomment-42316124).

2022-02-02 14:41 UTC, jakubdyszkiewicz approved these changes
thanks for fixing the edge case!

2022-02-02 14:45 UTC, merged