feat(kuma-cp): expose kuma-cp gui through ingress
kumahq/kuma pull request #4101
Opened 2022-04-01 02:28 UTC by lukidzi

### Summary

expose kuma-cp gui/api through ingress

### Full changelog

* [Implement helm ingress definition]

### Issues resolved

Fix #1117 

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [X] Manual testing on Kubernetes

### Backwards compatibility

- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.
- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)

2022-04-01 07:08 UTC, jakubdyszkiewicz requested changes

2022-04-01 07:08 UTC, jakubdyszkiewicz commented on deployments/charts/kuma/values.yaml
> +    # -- Install Kuma Control Plane with K8s Ingress resource
How about `Install K8s Ingress resource that exposes GUI and API`

2022-04-01 07:08 UTC, jakubdyszkiewicz commented on deployments/charts/kuma/templates/cp-ingress.yaml
> +      - path: /
I think we need more params here. For example kong has
```
  # Kong admin ingress settings. Useful if you want to expose the Admin
  # API of Kong outside the k8s cluster.
  ingress:
    # Enable/disable exposure using ingress.
    enabled: false
    ingressClassName:
    # TLS secret name.
    # tls: kong-admin.example.com-tls
    # Ingress hostname
    hostname:
    # Map of ingress annotations.
    annotations: {}
    # Ingress path.
    path: /
    # Each path in an Ingress is required to have a corresponding path type. (ImplementationSpecific/Exact/Prefix)
    pathType: ImplementationSpecific
```

Usually this ingress is a part of one gateway so we cannot just expose it on `*` hostname with `/` prefix.

2022-04-05 08:02 UTC, jakubdyszkiewicz approved these changes

2022-04-05 08:40 UTC, lahabana commented
As this is ready should we just merge it?

2022-04-05 10:59 UTC, merged