chore(*): remove flag '--experimental-meshgateway'
kumahq/kuma pull request #4315
Opened 2022-05-20 11:09 UTC by lobkovilya

### Summary

Remove flag `--experimental-meshgateway`

### Full changelog

* [Implement ...]
* [Fix ...]

### Issues resolved

Fix https://github.com/kumahq/kuma/issues/4263

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.
- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)

2022-05-20 11:41 UTC, jakubdyszkiewicz approved these changes

2022-05-23 06:39 UTC, michaelbeaumont requested changes
There are a few things missing here with `helm.sh` and `MeshGatewayConfig`, I'm taking a look

2022-05-23 09:09 UTC, michaelbeaumont approved these changes

2022-05-23 09:10 UTC, michaelbeaumont commented
Maybe @jakubdyszkiewicz can take another look at my changes

2022-05-23 10:15 UTC, merged