test(e2e): use different KDS port
kumahq/kuma pull request #6366
Opened 2023-03-28 12:00 UTC by michaelbeaumont

This conflicts with the default `nodePort` for the `global-zone-sync` `Service` and a Helm install is run concurrently with this test leading to flakes:

https://app.circleci.com/pipelines/github/kumahq/kuma/20794/workflows/68999f88-2cef-49e3-8a68-332c1a9fb6c8/jobs/365684

The `kdsPort` constants were messy and being used for both Helm and Universal tests.

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2023-04-18 09:00 UTC, lahabana commented
Seems like the latest flake would have been avoided with this: https://app.circleci.com/pipelines/gh/kumahq/kuma/21373/workflows/bf6bf773-e21e-4929-ac8c-2a1eb3c00fe0/jobs/384655

2023-04-24 07:34 UTC, bartsmykla requested changes

2023-04-24 07:34 UTC, bartsmykla commented on test/framework/interface.go
> -	GetXDSServerAddress() string
Please don't remove this as it's necessary for global ratelimit tests in kmesh

2023-04-24 08:06 UTC, bartsmykla approved these changes

2023-04-24 09:26 UTC, merged