feat(cni): k8s make namespace configurable
kumahq/kuma pull request #6721
Opened 2023-05-10 05:43 UTC by mmorel-35

### Checklist prior to review

- [ ] [Link to relevant issue][1] as well as docs and UI issues -- closes #6660 
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [ ] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2023-05-10 08:13 UTC, michaelbeaumont submitted a review, later dismissed

2023-05-10 09:24 UTC, michaelbeaumont commented on pkg/config/plugins/runtime/k8s/config.go
> +	CniPodNamespace string `json:"cniPodNamespace" envconfig:"kuma_runtime_kubernetes_node_taint_controller_cni_pod_namespace"`
Ah the node taint controller is running in the CP of course

2023-05-11 09:16 UTC, michaelbeaumont commented
I think this will need a change to the CNI manifests in the helm chart as well:

https://github.com/kumahq/kuma/blob/193d7d7a619fb7eff2fbd1caffd3f370098c3feb/deployments/charts/kuma/templates/cni-daemonset.yaml#L6

2023-05-15 17:07 UTC, michaelbeaumont requested changes

2023-05-15 17:07 UTC, michaelbeaumont commented on deployments/charts/kuma/values.yaml
> +  podNamespace: kube-system
```suggestion
  namespace: kube-system
```

2023-05-15 17:07 UTC, michaelbeaumont commented on pkg/config/plugins/runtime/k8s/config.go
> +	CniPodNamespace string `json:"cniPodNamespace" envconfig:"kuma_runtime_kubernetes_node_taint_controller_cni_pod_namespace"`
```suggestion
	CniNamespace string `json:"cniNamespace" envconfig:"kuma_runtime_kubernetes_node_taint_controller_cni_namespace"`
```

2023-05-16 08:42 UTC, michaelbeaumont approved these changes
LGTM, @bartsmykla can you take a look?

2023-05-16 11:42 UTC, bartsmykla approved these changes

2023-05-16 11:47 UTC, merged

2023-05-16 11:48 UTC, bartsmykla commented
Thank you @mmorel-35 for the contribution!