Ensure that duplicate listeners are not added when crossMesh is enabled on a listener and Routes specify hostnames
kumahq/kuma pull request #8156
Opened 2023-10-26 12:49 UTC by ttreptow

In the cross-mesh case, the SNI string will be a kuma SNI string for the gateway service (e.g. edge-gateway{mesh=default,port=tcp-8080}). Thus it is not possible to distinguish hosts at the listener level and no filter chain sni matchers are added. This can lead to a duplicate listener filter chain being added if there are multiple hostnames to route.

Thus we truncate the gatewayHosts array to size 1 before creating the listener blocks.

Fixes #8076 

Supersedes #8105 
* The approach in my PR solves the problem in a way that leaves the door open for host-based cross-mesh routing (i.e. specifying mesh hostnames in MeshGatewayRoute). I have that working and will submit a follow on PR for it
* The tests in this PR are modified from the ones in #8105, the authorship of the original tests was lost in some git rebasing

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) -- I don't think this needs to be backported 

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2023-10-26 12:58 UTC, ttreptow commented
I accidentally re-incorporated @michaelbeaumont 's changes while rebasing :see_no_evil: . I'm going to push a fixed commit in a minute

2023-10-27 07:43 UTC, michaelbeaumont commented on pkg/plugins/runtime/gateway/generator.go
> +		//for cross-mesh, we can only add one listener filter chain as there will not be any (usable) SNI available for filter chain matching
`gocritic` is complaining

```suggestion
		// for cross-mesh, we can only add one listener filter chain as there will not be any (usable) SNI available for filter chain matching
```

2023-10-27 15:13 UTC, michaelbeaumont commented on pkg/plugins/runtime/gateway/gateway_route_generator_test.go
> +    tags:
I'd like to avoid changing the existing test cases, can we leave the listener and existing MeshGatewayRoutes untouched?

2023-10-31 08:43 UTC, michaelbeaumont requested changes

2023-10-31 08:43 UTC, michaelbeaumont commented on pkg/plugins/runtime/gateway/generator.go
> +		gatewayHosts = gatewayHosts[:1]
Let's add this truncation to https://github.com/kumahq/kuma/blob/09097f213741535e7716703f92c5680188a7095d/pkg/plugins/runtime/gateway/filter_chain_generator.go#L94-L96

instead

2023-10-31 20:43 UTC, michaelbeaumont commented
@ttreptow unfortunately you need to rebase and add the `--signoff` to satisfy the DCO

2023-10-31 21:53 UTC, michaelbeaumont approved these changes
Thanks @ttreptow !

2023-11-01 13:22 UTC, merged